### ISSUE TITLE
shed command

### ISSUE THREAD

**Issue by mnowotnik** [romkatv/zsh-defer#10]
Why not just use shed command from the zsh/sched modulke?

**Comment by romkatv** [comment]
Sure, go ahead.

**Comment by mnowotnik** [comment]
@romkatv I didn't mean to be rude. I just wanted to know what are the benefits of using this tool over shed :)

**Comment by romkatv** [comment]
They are different tools.

**Comment by mnowotnik** [comment]
![Screenshot from 2022-06-12 23-23-58](https://user-images.githubusercontent.com/8244123/173254210-f81f3e93-da75-4c97-89af-be5e22ca97b4.png)

@romkatv 
They seem pretty similar to me

**Comment by romkatv** [comment]
Check the docs of both tools.

**Comment by mnowotnik** [comment]
Sure.

Differences:
- zsh-defer can't print to stdout
- sched has less features

Similarities:
- both execute commands when a shell is waiting for a user input

Moreover, in the zsh-defer README, it's written: 
> zsh-defer defers execution of a zsh command  until zsh has nothing else to do and is waiting for user input. Its intended purpose is staged zsh startup. It works similarly to Turbo mode in [zini](https://github.com/zdharma-continuum/zinit)

..and the reason Turbo mode works in zinit is that zinit-scheduler is being run periodically by sched

**Comment by romkatv** [comment]
> * zsh-defer can't print to stdout

This is incorrect.

> Similarities:
> 
> * both execute commands when a shell is waiting for a user input

sched can execute commands from precmd or zle, while zsh-defer executes all commands from zle. This makes sched unusable for the primary use case of zsh-defer.

To sum up, sched and zsh-defer are different tools. Their differences are in their respective documentations.

**Comment by mnowotnik** [comment]
Alright, thanks for clarification regarding precmd. That's what I was missing.

> This makes sched unusable for the primary use case of zsh-defer.

Well, it's good enough for zinit to use and I don't feel any delays while using zinit, but of course only a proper benchmark would tell the difference.

**Comment by romkatv** [comment]
> > This makes sched unusable for the primary use case of zsh-defer.
> 
> Well, it's good enough for zinit to use and I don't feel any delays while using zinit, but of course only a proper benchmark would tell the difference.

zinit turbo mode != shed. zinit turbo mode uses sched but it also uses for loops. Clearly for loop != zinit turbo mode.

**Comment by romkatv** [comment]
This might prove useful if you haven't see it yet: https://github.com/romkatv/zsh-bench#deferred-initialization

**Comment by mnowotnik** [comment]
That's informative. Thanks!
