### ISSUE TITLE
Using $0 from autoload function 

### ISSUE THREAD

**Issue by psprint** [romkatv/zsh-defer#2]
I'm not currently at a computer, so I cannot check, however shouldn't the `source` line:

```zsh
if (( ! $+_defer_tasks )); then
    source ${0:A:h}/zsh-defer.plugin.zsh
fi
```
use something like `$funcfiletrace` or some parameter like `$ZSH_DEFER_DIR`?

**Comment by romkatv** [comment]
Thanks for the report! Fixed.
