### ISSUE TITLE
Multiple empty prompt lines under tmux?

### ISSUE THREAD

**Issue by tmpm697** [romkatv/zsh-defer#9]
Tmux version
```
tmux -V
tmux next-3.4
```

Power10k latest version till commit hash: 0b02654

Terminal:
```
alacritty --version
alacritty 0.10.1 (2844606d)
```

If I load `zsh-autosuggestions.zsh`: `source ./plugins/zsh-autosuggestions/zsh-autosuggestions.zsh`, there're no multiple empty prompt lines.

But if I do `zsh-defer source ./plugins/zsh-autosuggestions/zsh-autosuggestions.zsh`, there'll multiple empty prompt lines after issued commands, number of empty lines is arbitrary like below:
```
my10kprompt%
my10kprompt%
my10kprompt%
my10kprompt%
my10kprompt%
my10kprompt%
my10kprompt%
my10kprompt% diff -u test1 test2
<..>
```
I scroll up `tmux` or `alacritty` to check those empty lines.

**Comment by romkatv** [comment]
Thanks for reporting this.

I won't be debugging this as I'm short on free time. If you find out the reason, please post an update.

**Comment by tmpm697** [comment]
This issue happens with every zsh-defer lines that I have in `.zshrc` and other files, meaning when you have 1/2 zsh-defer in `.zshrc`, start `alacritty` or `tmux` and immediatelly scroll up, empty prompt lines will appear.

**Comment by tmpm697** [comment]
It seems I can only produce this issue with tmux with the same zsh setup as alacritty.

**Comment by romkatv** [comment]
OK. I'm still not going to debug this. Sorry.

**Comment by tmpm697** [comment]
I think this dues to `tmux`, tried current 3.2 official and `-git` on arch, both keep have empty prompt lines when start `tmux` and did a scroll up. Not observe this issue on `alacritty`.

I did try `tmux -f /dev/null` and the issue still happens, so blame `tmux` but what the issue, idk.

**Comment by tmpm697** [comment]
Check [this](https://github.com/tmux/tmux/issues/3171)
